language: dart

services:
  - docker

dart:
  - stable

before_install:
  - ./tool/rebuild.sh

script:
  - pub run test test/all.dart
  # - pub global activate coverage
  # - dart --observe=8111 test/all.dart &
  # - sleep 10
  # - pub global run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates
  # - pub global run coverage:format_coverage --packages=.packages --report-on lib --in coverage.json --out lcov.info --lcov

after_success:
  # - bash <(curl -s https://codecov.io/bash)
