name: 'kafka'
version: 0.1.0
description: Kafka Client library for Dartlang
homepage: https://github.com/pulyaevskiy/dart-kafka
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.12.0 <3.0.0'

dependencies:
  quiver: "2.1.5"
  logging: "0.11.4"

dev_dependencies:
  test: "1.8.0"
  mockito: "4.1.1+1"
  dart_coveralls: "0.6.0+4"
